;Parsnp configuration File
;
[Reference]
file=parsnp_X13/X13.fasta.ref
reverse=0
[Query]
file1=except_X13/20HP1591.fasta
reverse1=0
file2=except_X13/20HP1594.fasta
reverse2=0
file3=except_X13/20HP1597.fasta
reverse3=0
file4=except_X13/20HP1608-1.fasta
reverse4=0
file5=except_X13/20HP1608-2.fasta
reverse5=0
file6=except_X13/20HP1614.fasta
reverse6=0
file7=except_X13/20HP1615.fasta
reverse7=0
file8=except_X13/62XEKK5.fasta
reverse8=0
file9=except_X13/66b.fasta
reverse9=0
file10=except_X13/69-1.fasta
reverse10=0
file11=except_X13/87-13.fasta
reverse11=0
file12=except_X13/87-7.fasta
reverse12=0
file13=except_X13/90-13.fasta
reverse13=0
file14=except_X13/DC99P1A1.fasta
reverse14=0
file15=except_X13/DC99P1B1.fasta
reverse15=0
file16=except_X13/DOA-1721.fasta
reverse16=0
file17=except_X13/DOA-1726.fasta
reverse17=0
file18=except_X13/DOA-2036.fasta
reverse18=0
file19=except_X13/DOA-2983.fasta
reverse19=0
file20=except_X13/DOA-2987.fasta
reverse20=0
file21=except_X13/DOA-2989.fasta
reverse21=0
file22=except_X13/Tu-10.fasta
reverse22=0
file23=except_X13/VTM10.fasta
reverse23=0
file24=except_X13/VTM12.fasta
reverse24=0
file25=except_X13/VTM15.fasta
reverse25=0
file26=except_X13/VTM16.fasta
reverse26=0
file27=except_X13/VTM4.fasta
reverse27=0
file28=except_X13/X22.fasta
reverse28=0
file29=except_X13/X31.fasta
reverse29=0
file30=except_X13/XCVCP-C-43.fasta
reverse30=0
file31=except_X13/XCVCP-C-51.fasta
reverse31=0
file32=except_X13/XCVKK-C-1.fasta
reverse32=0
file33=except_X13/XCVKK-C-2.fasta
reverse33=0
file34=except_X13/XCVKK-C-3.fasta
reverse34=0
file35=except_X13/XCVKK-C-4.fasta
reverse35=0
file36=except_X13/XCVKK-C-5.fasta
reverse36=0
file37=except_X13/Xcv_DC_96-3.fasta
reverse37=0
file38=except_X13/Xcv_DC_96-5.fasta
reverse38=0
file39=except_X13/Xcv_DC_97_P1A.fasta
reverse39=0
file40=except_X13/Xe173.fasta
reverse40=0
[MUM]
anchors=1.1*(Log(S))
anchorfile=
anchorsonly=0
calcmumi=1
mums=1.1*(Log(S))
mumfile=
filter=1
factor=2.0
extendmums=0
[LCB]
recombfilter=0
cores=1
diagdiff=0.12
doalign=2
c=21
d=300
q=30
p=15000000
icr=0
unaligned=$UNALIGNED
[Output]
outdir=parsnp_X13
prefix=parsnp
showbps=1

